### PR TITLE
Case insensitive q

### PR DESCRIPTION
**Pull request by DashKazak**
#9 addressed. See ui.py line 10, method is upper added

### CODE REVIEW

**Comment by wyatt-geiger** [comment]
It appears this branch was branched from book_read_confirmation which in turn was branched from no_duplicate_books_validation. Essentially, this is a branch within a branch with a branch within a branch. It should only be branched from main

**Review by DashKazak — COMMENTED** [review]
Solving the branch within a branch conflict by reverting some changes. Since it's just a couple lines of code, this method seems the easiest.

**Comment by DashKazak** [comment]
Please review. There was a branch within a branch conflict, which I believe I solved by reverting some changes and pulling my local repo to be up to date our remote repo.

**Comment by wyatt-geiger** [comment]
Just need to fix the merge conflict on this one

**Comment by wyatt-geiger** [comment]
It looks like the add_book() method contains nothing here. I would try to put the original code back in it from Clara's repo if you aren't already doing that

**Comment by wyatt-geiger** [comment]
LGTM

**Pull request merged**
