### PR TITLE
Book read confirmation

### PR DESCRIPTION
**Pull request by DashKazak**
Here I added an if/else statement that print's out a statement to the user, notifying of a status change. refer to  #10

### CODE REVIEW

**Comment by wyatt-geiger** [comment]
A couple of issues here:

- Looks like there is a branch conflict here. It seems this branch was branched from no_duplicate_books_validation when it should have been branched from main
- The solution for this issue should be in the change_read() method, not in the show_read_books() method. You are not changing the read status in show_read_books(), you are just viewing what the read status is

Also make sure to resolve merge conflicts

**Comment by DashKazak** [comment]
Hi @wyatt-geiger , I don't see changes made in in read_book function, my change was if/else statement in change_read, could you elaborate on your comment?

**Comment by wyatt-geiger** [comment]
> Hi @wyatt-geiger , I don't see changes made in in read_book function, my change was if/else statement in change_read, could you elaborate on your comment?

Yeah you can disregard the second bullet point, the way the editor showed it looked funny at first, but you're correct

**Comment by wyatt-geiger** [comment]
LGTM

**Pull request merged**
